# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wuX4PwLzDaWbAYLxGqKhQxXVtfwp3OLJ
"""

import pandas as pd
import numpy as np

train_data = pd.read_csv("nba_stats_dataset.csv")
train_data = train_data.drop(['Unnamed: 0', 'player_id', 'player'], axis=1)
print(train_data)
train_data_np = train_data.to_numpy()

print(train_data_np.shape)

X = train_data_np[:,:-1]
y = train_data_np[:,-1]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, max_iter=100000).fit(X_train, y_train)

y_pred = clf.predict(X_test)

from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred.round()))

"""Sanity check: let's check Stephen Curry's HOF probability."""

steph = np.array([846,840.0,29055.0,7089,14933,3220.0,7526.0,3294,3627,565.0,3407.0,3972.0,5528,1389.0,191.0,2657.0,2023,20692])

pred = clf.predict_proba(steph.reshape(1, -1))
print(pred)

import pickle
pickle.dump(clf, open('final_model.pkl', 'wb'))

